# -*- coding: utf-8 -*-
"""GitHub_Copilot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10bqbOOfNMRJtsNcSN-ROv0D94_qYALZr

# GitHub Copilot

copyright 2023, Denis Rothman, MIT License
"""

Print("GitHub Copilot")